/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventanas;

import Utilidades.GestionDatos;
import Utilidades.Usuario;
import Utilidades.Validador;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author NATALIA
 */
public class ActualizarInformacion extends javax.swing.JFrame {

    /**
     * Creates new form ActualizarInformacion
     */
    public ActualizarInformacion() {
        initComponents();
        this.setDefaultCloseOperation(HIDE_ON_CLOSE);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        campoNombre = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        campoBuscarID = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        campoEmail = new javax.swing.JFormattedTextField();
        campoTipoDocumento = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        campoCelular = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        campoEdad = new javax.swing.JFormattedTextField();
        agregar = new javax.swing.JButton();
        salir = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        campoNumDocumento = new javax.swing.JFormattedTextField();
        buscarButton = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(230, 223, 229));

        jLabel2.setFont(new java.awt.Font("Georgia", 0, 22)); // NOI18N
        jLabel2.setText("Número de documento");

        campoNombre.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        campoNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNombreActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Georgia", 0, 22)); // NOI18N
        jLabel3.setText("Nombre completo");

        campoBuscarID.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        campoBuscarID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoBuscarIDActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Georgia", 0, 22)); // NOI18N
        jLabel4.setText("Correo electrónico");

        campoEmail.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        campoEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoEmailActionPerformed(evt);
            }
        });

        campoTipoDocumento.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        campoTipoDocumento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cédula", "Tarjeta de identidad", "Cédula de extranjería", "Pasaporte" }));
        campoTipoDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTipoDocumentoActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Georgia", 0, 22)); // NOI18N
        jLabel5.setText("Tipo de documento");

        jLabel6.setFont(new java.awt.Font("Georgia", 0, 22)); // NOI18N
        jLabel6.setText("Número telefónico");

        campoCelular.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        campoCelular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoCelularActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Georgia", 0, 22)); // NOI18N
        jLabel7.setText("Edad");

        campoEdad.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        campoEdad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoEdadActionPerformed(evt);
            }
        });

        agregar.setBackground(new java.awt.Color(231, 185, 187));
        agregar.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        agregar.setText("Actualizar");
        agregar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarActionPerformed(evt);
            }
        });

        salir.setBackground(new java.awt.Color(231, 185, 187));
        salir.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        salir.setText("Salir");
        salir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });

        jSeparator1.setBackground(new java.awt.Color(231, 185, 187));
        jSeparator1.setForeground(new java.awt.Color(231, 185, 187));

        campoNumDocumento.setEditable(false);
        campoNumDocumento.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        campoNumDocumento.setDisabledTextColor(new java.awt.Color(0, 0, 204));
        campoNumDocumento.setEnabled(false);
        campoNumDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNumDocumentoActionPerformed(evt);
            }
        });

        buscarButton.setBackground(new java.awt.Color(231, 185, 187));
        buscarButton.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        buscarButton.setText("Buscar");
        buscarButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        buscarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarButtonActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Georgia", 0, 22)); // NOI18N
        jLabel9.setText("Número de documento");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(116, 116, 116)
                .addComponent(salir, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(346, 346, 346))
            .addComponent(jSeparator1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addComponent(jLabel9)
                        .addGap(60, 60, 60)
                        .addComponent(campoBuscarID, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(buscarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(205, 205, 205)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(campoEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel7)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel6))
                                    .addGap(198, 198, 198)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(campoCelular)
                                        .addComponent(campoTipoDocumento, javax.swing.GroupLayout.Alignment.TRAILING, 0, 157, Short.MAX_VALUE)
                                        .addComponent(campoEmail, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(campoNumDocumento, javax.swing.GroupLayout.Alignment.TRAILING)))))))
                .addContainerGap(177, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoBuscarID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(52, 52, 52)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(campoEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(campoTipoDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(campoNumDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(campoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(salir, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNombreActionPerformed

    private void campoBuscarIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoBuscarIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoBuscarIDActionPerformed

    private void campoEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoEmailActionPerformed

    private void campoTipoDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTipoDocumentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoTipoDocumentoActionPerformed

    private void campoCelularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoCelularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoCelularActionPerformed

    private void campoEdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoEdadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoEdadActionPerformed

    private void agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarActionPerformed
        // TODO add your handling code here:

        if (campoNumDocumento.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor ingresa un número de documento para continuar.\nEn caso de que lo hayas hecho, verifica si tiene registro.", "Error", JOptionPane.WARNING_MESSAGE);
            return; // Salimos del método si el campo de documento está vacío
        }
        
        
        
        // Verificar si los campos están vacíos
            
        if (campoNumDocumento.getText().isEmpty() ||
            campoNombre.getText().isEmpty() ||
            campoEdad.getText().isEmpty() ||
            campoTipoDocumento.getSelectedItem() == null ||
            campoEmail.getText().isEmpty() ||
            campoCelular.getText().isEmpty()) {
            
        
            // Mostrar mensaje de advertencia
            JOptionPane.showMessageDialog(this, "Asegúrate de que ningún campo esté vacío.\nRecuerda que todos los campos son obligatorios.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return; // Salir del método si hay campos vacíos
        }
    
    
        List<String> errores = new ArrayList<>();

        String numDocumento = campoNumDocumento.getText();
        String nombre = campoNombre.getText();
        //int edad = Integer.parseInt(campoEdad.getText());
        String tipoDocumento = (String) campoTipoDocumento.getSelectedItem();
        String email = campoEmail.getText();
        String celular = campoCelular.getText();
        boolean estado = true;
        String curso = "";
        String evento = ""; 


        if (nombre.isEmpty() || campoEdad.getText().isEmpty() || 
            tipoDocumento == null || numDocumento.isEmpty() || 
            email.isEmpty() || celular.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ningún campo puede estar vacío.", 
                "Mensaje", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int edad;
        try {
            edad = Integer.parseInt(campoEdad.getText());
        } catch (NumberFormatException e) {
            edad = -1;
        }
        if (!Validador.nombreValido(nombre)) {
            errores.add("El nombre solo puede contener letras y espacios.");
        }
        if (!Validador.edadValida(edad)) {
            errores.add("La edad debe ser un número positivo entre 9 y 50.");
        }
        if (!Validador.numDocumentoValido(numDocumento)) {
            errores.add("El número de documento debe contener 10 dígitos (números).");
        }
        if (!Validador.correoValido(email)) {
            errores.add("El correo tiene un formato inválido (ej: usuario@example.com).");
        }
        if (!Validador.celularValido(celular)) {
            errores.add("El celular debe tener exactamente 10 dígitos (números).");
        }


        // Mostrar errores si existen
        if (!errores.isEmpty()) {
            JOptionPane.showMessageDialog(this, String.join("\n", errores), 
                "Errores de validación", JOptionPane.ERROR_MESSAGE);
            return;
        }
        Usuario nuevosDatos = new Usuario(nombre, edad, tipoDocumento, numDocumento, email, celular, estado, curso, evento);
        GestionDatos gestion = new GestionDatos();
        gestion.leerCSV("RegistroUsuario.csv"); // Cargar usuarios

        if (gestion.actualizarUsuario(numDocumento, nuevosDatos)) {
            JOptionPane.showMessageDialog(this, "¡Su información fue actualizada con éxito!");
            gestion.guardarEnCSV("RegistroUsuario.csv"); // Guardar los cambios en el CSV
        } else {
        JOptionPane.showMessageDialog(this, "Usuario no encontrado para actualizar.");
        }  
                                    
    }//GEN-LAST:event_agregarActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        // TODO add your handling code here:
        Index ventanaIndex = new Index();
        this.setVisible(false);
        ventanaIndex.setVisible(true);
    }//GEN-LAST:event_salirActionPerformed

    private void campoNumDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNumDocumentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNumDocumentoActionPerformed

    private void buscarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarButtonActionPerformed
        // TODO add your handling code here:
        
        
        String numDocumento = campoBuscarID.getText();
        GestionDatos gestion = new GestionDatos();
        
        if (numDocumento.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor ingresa un número de documento para buscar.", "Campo Vacío", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
            // Validar que el número de documento tenga exactamente 10 dígitos
        if (numDocumento.length() != 10 || !numDocumento.matches("\\d+")) {
            JOptionPane.showMessageDialog(this, "Recuerda que el número de documento solo contiene 10 dígitos.", "Error de Validación", JOptionPane.ERROR_MESSAGE);
            return; // Salimos del método si el documento no es válido
        }
        
        gestion.leerCSV("RegistroUsuario.csv");  

        Usuario usuario = gestion.buscarID(numDocumento);

        if (usuario != null) {
            
            // Mostrar los datos del usuario en los JTextField
            campoNombre.setText(usuario.getNombre());
            campoEdad.setText(String.valueOf(usuario.getEdad()));
            campoTipoDocumento.setSelectedItem(usuario.getTipoDocumento());
            campoNumDocumento.setText(usuario.getNumeroDocumento());
            campoEmail.setText(usuario.getEmail());
            campoCelular.setText(usuario.getCelular());
                 
            
        } else {
            JOptionPane.showMessageDialog(this, "No se encontró ningún usuario con el documento ingresado.", "Usuario No Encontrado", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_buscarButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ActualizarInformacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ActualizarInformacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ActualizarInformacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ActualizarInformacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ActualizarInformacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregar;
    private javax.swing.JButton buscarButton;
    private javax.swing.JFormattedTextField campoBuscarID;
    private javax.swing.JFormattedTextField campoCelular;
    private javax.swing.JFormattedTextField campoEdad;
    private javax.swing.JFormattedTextField campoEmail;
    private javax.swing.JFormattedTextField campoNombre;
    private javax.swing.JFormattedTextField campoNumDocumento;
    private javax.swing.JComboBox<String> campoTipoDocumento;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton salir;
    // End of variables declaration//GEN-END:variables
}
