/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventanas;
import Utilidades.Usuario;
import Utilidades.GestionDatos;
import javax.swing.JOptionPane;
/**
 *
 * @author NATALIA
 */
public class ConstanciaCursosInscritos extends javax.swing.JFrame {
private Usuario usuario;  //variable de clase para almacenar el usuario encontrado
private final GestionDatos GESTION = new GestionDatos();
    /**
     * Creates new form ConstanciaCursosInscritosNuevaVersion
     */
    public ConstanciaCursosInscritos() {
        initComponents();
        this.setDefaultCloseOperation(HIDE_ON_CLOSE);
        this.setLocationRelativeTo(null);
        descargarConstanciaCursosInscritos.setVisible(false);
        GESTION.leerCSV("RegistroUsuario.csv"); //cargamos el csv
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ingresarUsuarioBaileC1 = new javax.swing.JFormattedTextField();
        descargarConstanciaCursosInscritos = new javax.swing.JButton();
        buscarButton = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        eventosDisponibles = new javax.swing.JLabel();
        salir = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        campoCurso = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(230, 223, 229));
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 644));

        ingresarUsuarioBaileC1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ingresarUsuarioBaileC1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresarUsuarioBaileC1ActionPerformed(evt);
            }
        });

        descargarConstanciaCursosInscritos.setBackground(new java.awt.Color(231, 185, 187));
        descargarConstanciaCursosInscritos.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        descargarConstanciaCursosInscritos.setText("Descargar constancia de cursos inscritos");
        descargarConstanciaCursosInscritos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        descargarConstanciaCursosInscritos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descargarConstanciaCursosInscritosActionPerformed(evt);
            }
        });

        buscarButton.setBackground(new java.awt.Color(231, 185, 187));
        buscarButton.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        buscarButton.setText("Buscar");
        buscarButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        buscarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarButtonActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Georgia", 0, 22)); // NOI18N
        jLabel9.setText("Número de documento");

        eventosDisponibles.setBackground(new java.awt.Color(0, 0, 0));
        eventosDisponibles.setFont(new java.awt.Font("Georgia", 1, 42)); // NOI18N
        eventosDisponibles.setText("Constancia de Cursos Inscritos");

        salir.setBackground(new java.awt.Color(231, 185, 187));
        salir.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        salir.setText("Salir");
        salir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Georgia", 0, 22)); // NOI18N
        jLabel10.setText("Curso");

        campoCurso.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        campoCurso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Arte Dramático", "Baile Contemporáneo", "Ballet Básico", "Ballet Juvenil", "Canto", "Dibujo", "Piano" }));
        campoCurso.setBorder(null);
        campoCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoCursoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(189, 189, 189)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(campoCurso, 0, 1, Short.MAX_VALUE)
                    .addComponent(ingresarUsuarioBaileC1, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE))
                .addGap(198, 198, 198))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(eventosDisponibles))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(355, 355, 355)
                        .addComponent(descargarConstanciaCursosInscritos, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(275, 275, 275)
                        .addComponent(buscarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(128, 128, 128)
                        .addComponent(salir, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(186, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(eventosDisponibles)
                .addGap(82, 82, 82)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(ingresarUsuarioBaileC1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(campoCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buscarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(salir, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addComponent(descargarConstanciaCursosInscritos, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(118, 118, 118))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ingresarUsuarioBaileC1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresarUsuarioBaileC1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ingresarUsuarioBaileC1ActionPerformed

    private void descargarConstanciaCursosInscritosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descargarConstanciaCursosInscritosActionPerformed
        String nombre = usuario.getNombre();
        String tipoId = usuario.getTipoDocumento();
        String id = usuario.getNumeroDocumento();
        String curso = (String) campoCurso.getSelectedItem();
        GESTION.crearPdfConstanciaCurso(this, nombre, tipoId, id, curso);
    }//GEN-LAST:event_descargarConstanciaCursosInscritosActionPerformed

    private void buscarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarButtonActionPerformed
        descargarConstanciaCursosInscritos.setVisible(false);
        String numDoc = ingresarUsuarioBaileC1.getText();
        String curso = (String) campoCurso.getSelectedItem();
        if (numDoc.isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                "Por favor, ingresa el número de documento.", 
                "Campo Vacío", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        usuario = GESTION.buscarConCurso(numDoc, curso);
        if ((usuario != null) && (usuario.getCurso().equals(curso))){
                JOptionPane.showMessageDialog(this, "Ya puede descargar su constancia de matrícula", "Constancia de matrícula", JOptionPane.INFORMATION_MESSAGE);
                descargarConstanciaCursosInscritos.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Usted no se encuentra matrículado en " + curso, "Constancia de matrícula", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_buscarButtonActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        // TODO add your handling code here:
        Index ventanaIndex = new Index();
        this.setVisible(false);
        ventanaIndex.setVisible(true);
    }//GEN-LAST:event_salirActionPerformed

    private void campoCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoCursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoCursoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConstanciaCursosInscritos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConstanciaCursosInscritos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConstanciaCursosInscritos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConstanciaCursosInscritos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConstanciaCursosInscritos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscarButton;
    private javax.swing.JComboBox<String> campoCurso;
    private javax.swing.JButton descargarConstanciaCursosInscritos;
    private javax.swing.JLabel eventosDisponibles;
    private javax.swing.JFormattedTextField ingresarUsuarioBaileC1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton salir;
    // End of variables declaration//GEN-END:variables
}
