/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventanas;

/**
 *
 * @author USUARIO
 */
public class Cursos extends javax.swing.JFrame {

    /**
     * Creates new form Cursos
     */
    public Cursos() {
        initComponents();
        this.setDefaultCloseOperation(HIDE_ON_CLOSE);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jPanel1 = new javax.swing.JPanel();
        cursosDisponibles = new javax.swing.JLabel();
        balletB = new javax.swing.JLabel();
        balletJ = new javax.swing.JLabel();
        piano = new javax.swing.JLabel();
        baileC = new javax.swing.JLabel();
        arteDramatico = new javax.swing.JLabel();
        dibujo = new javax.swing.JLabel();
        canto = new javax.swing.JLabel();
        buttonVerMasBalletB = new javax.swing.JButton();
        buttonVerMasBalletJ = new javax.swing.JButton();
        buttonVerMasBaileC = new javax.swing.JButton();
        buttonVerMasPiano = new javax.swing.JButton();
        buttonVerMasDibujo = new javax.swing.JButton();
        buttonVerMasCanto = new javax.swing.JButton();
        buttonVerMasArteDramatico = new javax.swing.JButton();
        salir = new javax.swing.JButton();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(230, 223, 229));

        cursosDisponibles.setBackground(new java.awt.Color(230, 223, 229));
        cursosDisponibles.setFont(new java.awt.Font("Georgia", 1, 42)); // NOI18N
        cursosDisponibles.setText("Cursos Disponibles");
        cursosDisponibles.setAutoscrolls(true);
        cursosDisponibles.setOpaque(true);

        balletB.setFont(new java.awt.Font("Georgia", 0, 28)); // NOI18N
        balletB.setText("Ballet Básico");

        balletJ.setFont(new java.awt.Font("Georgia", 0, 28)); // NOI18N
        balletJ.setText("Ballet Juvenil");

        piano.setFont(new java.awt.Font("Georgia", 0, 28)); // NOI18N
        piano.setText("Piano");

        baileC.setFont(new java.awt.Font("Georgia", 0, 28)); // NOI18N
        baileC.setText("Baile Contemporáneo");

        arteDramatico.setFont(new java.awt.Font("Georgia", 0, 28)); // NOI18N
        arteDramatico.setText("Arte Dramático");

        dibujo.setFont(new java.awt.Font("Georgia", 0, 28)); // NOI18N
        dibujo.setText("Dibujo");

        canto.setFont(new java.awt.Font("Georgia", 0, 28)); // NOI18N
        canto.setText("Canto");

        buttonVerMasBalletB.setBackground(new java.awt.Color(231, 185, 187));
        buttonVerMasBalletB.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        buttonVerMasBalletB.setText("Ver más");
        buttonVerMasBalletB.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        buttonVerMasBalletB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonVerMasBalletBActionPerformed(evt);
            }
        });

        buttonVerMasBalletJ.setBackground(new java.awt.Color(231, 185, 187));
        buttonVerMasBalletJ.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        buttonVerMasBalletJ.setText("Ver más");
        buttonVerMasBalletJ.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        buttonVerMasBalletJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonVerMasBalletJActionPerformed(evt);
            }
        });

        buttonVerMasBaileC.setBackground(new java.awt.Color(231, 185, 187));
        buttonVerMasBaileC.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        buttonVerMasBaileC.setText("Ver más");
        buttonVerMasBaileC.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        buttonVerMasBaileC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonVerMasBaileCActionPerformed(evt);
            }
        });

        buttonVerMasPiano.setBackground(new java.awt.Color(231, 185, 187));
        buttonVerMasPiano.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        buttonVerMasPiano.setText("Ver más");
        buttonVerMasPiano.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        buttonVerMasPiano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonVerMasPianoActionPerformed(evt);
            }
        });

        buttonVerMasDibujo.setBackground(new java.awt.Color(231, 185, 187));
        buttonVerMasDibujo.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        buttonVerMasDibujo.setText("Ver más");
        buttonVerMasDibujo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        buttonVerMasDibujo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonVerMasDibujoActionPerformed(evt);
            }
        });

        buttonVerMasCanto.setBackground(new java.awt.Color(231, 185, 187));
        buttonVerMasCanto.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        buttonVerMasCanto.setText("Ver más");
        buttonVerMasCanto.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        buttonVerMasCanto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonVerMasCantoActionPerformed(evt);
            }
        });

        buttonVerMasArteDramatico.setBackground(new java.awt.Color(231, 185, 187));
        buttonVerMasArteDramatico.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        buttonVerMasArteDramatico.setText("Ver más");
        buttonVerMasArteDramatico.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        buttonVerMasArteDramatico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonVerMasArteDramaticoActionPerformed(evt);
            }
        });

        salir.setBackground(new java.awt.Color(231, 185, 187));
        salir.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        salir.setText("Salir");
        salir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(balletJ)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonVerMasBalletJ, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(balletB, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonVerMasBalletB, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(arteDramatico)
                        .addGap(428, 428, 428)
                        .addComponent(buttonVerMasArteDramatico, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(dibujo)
                            .addGap(535, 535, 535)
                            .addComponent(buttonVerMasDibujo, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(piano)
                                .addGap(549, 549, 549)
                                .addComponent(buttonVerMasPiano, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(baileC)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(buttonVerMasBaileC, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(canto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonVerMasCanto, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 135, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(416, 416, 416)
                .addComponent(salir, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cursosDisponibles)
                .addGap(276, 276, 276))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(cursosDisponibles, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(baileC)
                    .addComponent(buttonVerMasBaileC))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(balletJ)
                    .addComponent(buttonVerMasBalletJ))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(balletB, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonVerMasBalletB))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(piano, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonVerMasPiano))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dibujo)
                    .addComponent(buttonVerMasDibujo))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(arteDramatico)
                    .addComponent(buttonVerMasArteDramatico))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(canto)
                    .addComponent(buttonVerMasCanto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(salir, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        // TODO add your handling code here:
        Index ventanaIndex = new Index();
        this.setVisible(false);
        ventanaIndex.setVisible(true);
    }//GEN-LAST:event_salirActionPerformed

    private void buttonVerMasArteDramaticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonVerMasArteDramaticoActionPerformed
        // TODO add your handling code here
        VerMasArteDramatico ventanaVerMasArteDramatico = new VerMasArteDramatico();
        this.setVisible(false);
        ventanaVerMasArteDramatico.setVisible(true);
    }//GEN-LAST:event_buttonVerMasArteDramaticoActionPerformed

    private void buttonVerMasCantoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonVerMasCantoActionPerformed
        // TODO add your handling code here:
        VerMasCanto ventanaVerMasCanto = new VerMasCanto();
        this.setVisible(false);
        ventanaVerMasCanto.setVisible(true);
    }//GEN-LAST:event_buttonVerMasCantoActionPerformed

    private void buttonVerMasDibujoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonVerMasDibujoActionPerformed
        // TODO add your handling code here:
        VerMasDibujo ventanaVerMasDibujo = new VerMasDibujo();
        this.setVisible(false);
        ventanaVerMasDibujo.setVisible(true);
    }//GEN-LAST:event_buttonVerMasDibujoActionPerformed

    private void buttonVerMasPianoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonVerMasPianoActionPerformed
        // TODO add your handling code here:
        VerMasPiano ventanaVerMasPiano = new VerMasPiano();
        this.setVisible(false);
        ventanaVerMasPiano.setVisible(true);
    }//GEN-LAST:event_buttonVerMasPianoActionPerformed

    private void buttonVerMasBaileCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonVerMasBaileCActionPerformed
        // TODO add your handling code here:
        VerMasBaileC ventanaVerMasBalieC = new VerMasBaileC();
        this.setVisible(false);
        ventanaVerMasBalieC.setVisible(true);
    }//GEN-LAST:event_buttonVerMasBaileCActionPerformed

    private void buttonVerMasBalletJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonVerMasBalletJActionPerformed
        // TODO add your handling code here:
        VerMasBalletJ ventanaVerMasBalletJ = new VerMasBalletJ();
        this.setVisible(false);
        ventanaVerMasBalletJ.setVisible(true);
    }//GEN-LAST:event_buttonVerMasBalletJActionPerformed

    private void buttonVerMasBalletBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonVerMasBalletBActionPerformed
        // TODO add your handling code here:
        VerMasBalletB ventanaVerMasBalletB = new VerMasBalletB();
        this.setVisible(false);
        ventanaVerMasBalletB.setVisible(true);
    }//GEN-LAST:event_buttonVerMasBalletBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cursos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cursos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cursos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cursos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cursos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel arteDramatico;
    private javax.swing.JLabel baileC;
    private javax.swing.JLabel balletB;
    private javax.swing.JLabel balletJ;
    private javax.swing.JButton buttonVerMasArteDramatico;
    private javax.swing.JButton buttonVerMasBaileC;
    private javax.swing.JButton buttonVerMasBalletB;
    private javax.swing.JButton buttonVerMasBalletJ;
    private javax.swing.JButton buttonVerMasCanto;
    private javax.swing.JButton buttonVerMasDibujo;
    private javax.swing.JButton buttonVerMasPiano;
    private javax.swing.JLabel canto;
    private javax.swing.JLabel cursosDisponibles;
    private javax.swing.JLabel dibujo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JLabel piano;
    private javax.swing.JButton salir;
    // End of variables declaration//GEN-END:variables
}
