/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventanas;

import Utilidades.GestionDatos;
import Utilidades.Usuario;
import javax.swing.JOptionPane;


/**
 *
 * @author NATALIA
 */
public class EliminarRegistro extends javax.swing.JFrame {

    /**
     * Creates new form EliminarRegistro
     */
    public EliminarRegistro() {
        initComponents();
        this.setDefaultCloseOperation(HIDE_ON_CLOSE);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        campoNumDocumento = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        campoCurso = new javax.swing.JComboBox<>();
        eliminarRegistroButton = new javax.swing.JButton();
        salirButton = new javax.swing.JButton();
        buscarButton = new javax.swing.JButton();
        campoCuadro = new javax.swing.JTextField();
        cursosDisponibles = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(230, 223, 229));

        jLabel2.setFont(new java.awt.Font("Georgia", 0, 22)); // NOI18N
        jLabel2.setText("Número de documento");

        campoNumDocumento.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        campoNumDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNumDocumentoActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Georgia", 0, 22)); // NOI18N
        jLabel4.setText("Curso");

        campoCurso.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        campoCurso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Arte Dramático", "Baile Contemporáneo", "Ballet Básico", "Ballet Juvenil", "Canto", "Dibujo", "Piano" }));
        campoCurso.setBorder(null);
        campoCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoCursoActionPerformed(evt);
            }
        });

        eliminarRegistroButton.setBackground(new java.awt.Color(231, 185, 187));
        eliminarRegistroButton.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        eliminarRegistroButton.setText("Eliminar");
        eliminarRegistroButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        eliminarRegistroButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarRegistroButtonActionPerformed(evt);
            }
        });

        salirButton.setBackground(new java.awt.Color(231, 185, 187));
        salirButton.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        salirButton.setText("Salir");
        salirButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        salirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirButtonActionPerformed(evt);
            }
        });

        buscarButton.setBackground(new java.awt.Color(231, 185, 187));
        buscarButton.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        buscarButton.setText("Buscar");
        buscarButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        buscarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarButtonActionPerformed(evt);
            }
        });

        campoCuadro.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        campoCuadro.setText("Usuario: ");
        campoCuadro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoCuadroActionPerformed(evt);
            }
        });

        cursosDisponibles.setBackground(new java.awt.Color(230, 223, 229));
        cursosDisponibles.setFont(new java.awt.Font("Georgia", 1, 42)); // NOI18N
        cursosDisponibles.setText("Eliminación de Registro");
        cursosDisponibles.setAutoscrolls(true);
        cursosDisponibles.setOpaque(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addComponent(eliminarRegistroButton, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(132, 132, 132)
                        .addComponent(salirButton, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel2))
                                .addGap(164, 164, 164)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(campoNumDocumento, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                                    .addComponent(campoCurso, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(buscarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(campoCuadro, javax.swing.GroupLayout.PREFERRED_SIZE, 711, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(172, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(244, 244, 244)
                .addComponent(cursosDisponibles)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(cursosDisponibles, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(campoNumDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(buscarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(campoCuadro, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eliminarRegistroButton, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(salirButton, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(76, 76, 76))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoNumDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNumDocumentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNumDocumentoActionPerformed

    private void campoCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoCursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoCursoActionPerformed

    private void eliminarRegistroButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarRegistroButtonActionPerformed
        
        // TODO add your handling code here:
        String numDocumento = campoNumDocumento.getText();
        String curso = (String) campoCurso.getSelectedItem();

        // Validar que los campos no estén vacíos
        if (numDocumento.isEmpty() || curso == null || curso.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, complete todos los campos antes de eliminar.");
            return; // Salir del método si hay campos vacíos
        }
        
        GestionDatos gestion = new GestionDatos();
        gestion.leerCSV("RegistroUsuario.csv");  
        
        // Verificar si el usuario existe antes de intentar eliminarlo
        Usuario usuario = gestion.buscarParaEliminar(numDocumento, curso);
        if (usuario == null) {
            JOptionPane.showMessageDialog(this, "No se puede eliminar. El usuario no se encuentra registrado.");
            return; // Salir del método si el usuario no existe
        }

        
        gestion.eliminarUsuario(numDocumento, curso);
        JOptionPane.showMessageDialog(this, "¡Su información fue eliminada con éxito!");
        

    }//GEN-LAST:event_eliminarRegistroButtonActionPerformed

    private void salirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirButtonActionPerformed
        // TODO add your handling code here:
        Index ventanaIndex = new Index();
        this.setVisible(false);
        ventanaIndex.setVisible(true);
    }//GEN-LAST:event_salirButtonActionPerformed

    private void buscarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarButtonActionPerformed
        // TODO add your handling code here:
        String numeroDocumento = campoNumDocumento.getText();
        String curso = (String) campoCurso.getSelectedItem();
        GestionDatos gestion = new GestionDatos();
 
  
        gestion.leerCSV("RegistroUsuario.csv");  
        
        if (numeroDocumento.isEmpty()) {
            JOptionPane.showMessageDialog(this, "El campo de número de documento no puede estar vacío.");
            return;
        }
        
        // Validar que el número de documento tenga exactamente 10 dígitos
        if (numeroDocumento.length() != 10 || !numeroDocumento.matches("\\d+")) {
            JOptionPane.showMessageDialog(this, 
                "Recuerda que el número de documento solo contiene 10 dígitos.", 
                "Error de Validación", 
                JOptionPane.ERROR_MESSAGE);
            return; // Salimos del método si el documento no es válido
        }
        
        Usuario usuario = gestion.buscarParaEliminar(numeroDocumento, curso);

        if (usuario != null) {
            // Mostrar los datos del usuario en los JTextField
            campoCuadro.setText(usuario.getNombre());
        } else {
            JOptionPane.showMessageDialog(this, "Usuario no encontrado.\nNo hay registro asociado al número de documento y curso proporcionados.");
        }
    }//GEN-LAST:event_buscarButtonActionPerformed

    private void campoCuadroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoCuadroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoCuadroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EliminarRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EliminarRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EliminarRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EliminarRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EliminarRegistro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscarButton;
    private javax.swing.JTextField campoCuadro;
    private javax.swing.JComboBox<String> campoCurso;
    private javax.swing.JFormattedTextField campoNumDocumento;
    private javax.swing.JLabel cursosDisponibles;
    private javax.swing.JButton eliminarRegistroButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton salirButton;
    // End of variables declaration//GEN-END:variables
}
