/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventanas;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author USUARIO
 */
public class Eventos extends javax.swing.JFrame {

    /**
     * Creates new form Eventos
     */
    public Eventos() {
        initComponents();
        this.setDefaultCloseOperation(HIDE_ON_CLOSE);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel16 = new javax.swing.JPanel();
        jButton10 = new javax.swing.JButton();
        jPanel17 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        fondoOpera = new javax.swing.JPanel();
        inscribirmeTeatro = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        eventosDisponibles = new javax.swing.JLabel();
        opera = new javax.swing.JLabel();
        teatro = new javax.swing.JLabel();
        danza = new javax.swing.JLabel();
        opera1 = new javax.swing.JLabel();
        fondoOpera1 = new javax.swing.JPanel();
        inscribirmeOpera = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        fondoOpera4 = new javax.swing.JPanel();
        inscribirmeDanza = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        salir = new javax.swing.JButton();

        jPanel16.setBackground(new java.awt.Color(255, 255, 255));

        jButton10.setText("Inscribirme");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 253, Short.MAX_VALUE)
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 366, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(jButton10))
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton10)
                .addGap(22, 22, 22))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(230, 223, 229));

        jPanel2.setBackground(new java.awt.Color(230, 223, 229));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fondoOpera.setBackground(new java.awt.Color(255, 255, 255));
        fondoOpera.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        inscribirmeTeatro.setBackground(new java.awt.Color(231, 185, 187));
        inscribirmeTeatro.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        inscribirmeTeatro.setText("Inscribirme");
        inscribirmeTeatro.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        inscribirmeTeatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inscribirmeTeatroActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poster_teatro_final (1).jpg"))); // NOI18N

        javax.swing.GroupLayout fondoOperaLayout = new javax.swing.GroupLayout(fondoOpera);
        fondoOpera.setLayout(fondoOperaLayout);
        fondoOperaLayout.setHorizontalGroup(
            fondoOperaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoOperaLayout.createSequentialGroup()
                .addGroup(fondoOperaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fondoOperaLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel1))
                    .addGroup(fondoOperaLayout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(inscribirmeTeatro, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        fondoOperaLayout.setVerticalGroup(
            fondoOperaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fondoOperaLayout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(inscribirmeTeatro)
                .addGap(24, 24, 24))
        );

        jPanel2.add(fondoOpera, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 270, 460));

        eventosDisponibles.setBackground(new java.awt.Color(0, 0, 0));
        eventosDisponibles.setFont(new java.awt.Font("Georgia", 1, 42)); // NOI18N
        eventosDisponibles.setText("Eventos Disponibles");
        jPanel2.add(eventosDisponibles, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, -1, -1));

        opera.setFont(new java.awt.Font("Georgia", 0, 24)); // NOI18N
        opera.setText("Danza");
        jPanel2.add(opera, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 80, -1, -1));

        teatro.setFont(new java.awt.Font("Georgia", 0, 24)); // NOI18N
        teatro.setText("Teatro");
        jPanel2.add(teatro, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, -1, -1));

        danza.setFont(new java.awt.Font("Bodoni MT", 0, 24)); // NOI18N
        danza.setText("Danza");
        jPanel2.add(danza, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 110, -1, -1));

        opera1.setFont(new java.awt.Font("Georgia", 0, 24)); // NOI18N
        opera1.setText("Ópera");
        jPanel2.add(opera1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 90, -1, -1));

        fondoOpera1.setBackground(new java.awt.Color(255, 255, 255));
        fondoOpera1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        inscribirmeOpera.setBackground(new java.awt.Color(231, 185, 187));
        inscribirmeOpera.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        inscribirmeOpera.setText("Inscribirme");
        inscribirmeOpera.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        inscribirmeOpera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inscribirmeOperaActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poster_opera_final (1).jpg"))); // NOI18N

        javax.swing.GroupLayout fondoOpera1Layout = new javax.swing.GroupLayout(fondoOpera1);
        fondoOpera1.setLayout(fondoOpera1Layout);
        fondoOpera1Layout.setHorizontalGroup(
            fondoOpera1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoOpera1Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(fondoOpera1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fondoOpera1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fondoOpera1Layout.createSequentialGroup()
                        .addComponent(inscribirmeOpera, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83))))
        );
        fondoOpera1Layout.setVerticalGroup(
            fondoOpera1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fondoOpera1Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(inscribirmeOpera)
                .addGap(21, 21, 21))
        );

        jPanel2.add(fondoOpera1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 120, 270, 460));

        fondoOpera4.setBackground(new java.awt.Color(255, 255, 255));
        fondoOpera4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        inscribirmeDanza.setBackground(new java.awt.Color(231, 185, 187));
        inscribirmeDanza.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        inscribirmeDanza.setText("Inscribirme");
        inscribirmeDanza.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        inscribirmeDanza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inscribirmeDanzaActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poster_danza_final (1).jpg"))); // NOI18N

        javax.swing.GroupLayout fondoOpera4Layout = new javax.swing.GroupLayout(fondoOpera4);
        fondoOpera4.setLayout(fondoOpera4Layout);
        fondoOpera4Layout.setHorizontalGroup(
            fondoOpera4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoOpera4Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(24, 24, 24))
            .addGroup(fondoOpera4Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(inscribirmeDanza, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        fondoOpera4Layout.setVerticalGroup(
            fondoOpera4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fondoOpera4Layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(inscribirmeDanza)
                .addGap(17, 17, 17))
        );

        jPanel2.add(fondoOpera4, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 120, 270, 460));

        salir.setBackground(new java.awt.Color(231, 185, 187));
        salir.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        salir.setText("Salir");
        salir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        jPanel2.add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 600, 110, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 644, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inscribirmeTeatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inscribirmeTeatroActionPerformed

        String csvFile = "RegistroUsuario.csv";
        String line;
        String csvSplitBy = ";";
        int count = 0;

        try (BufferedReader br = new BufferedReader(new FileReader(csvFile))) {
            while ((line = br.readLine()) != null) {
                String[] data = line.split(csvSplitBy);
                if (data.length > 8 && "Teatro".equals(data[8])) {
                    count++;
                }
            }
        } catch (IOException e) {
            e.printStackTrace();
        }

        if (count >= 150) {
            JOptionPane.showMessageDialog(null, "No hay más boletas disponibles");
        } else {
            Global.eventoActual = "Teatro";
            Global.cursoActual = null;
            NuevoRegistro ventanaNuevoRegistro = new NuevoRegistro();
            this.setVisible(false);
            ventanaNuevoRegistro.setVisible(true);
        }
    }//GEN-LAST:event_inscribirmeTeatroActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void inscribirmeOperaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inscribirmeOperaActionPerformed

        String csvFile = "RegistroUsuario.csv";
        String line;
        String csvSplitBy = ";";
        int count = 0;

        try (BufferedReader br = new BufferedReader(new FileReader(csvFile))) {
            while ((line = br.readLine()) != null) {
                String[] data = line.split(csvSplitBy);
                if (data.length > 8 && "Ópera".equals(data[8])) {
                    count++;
                }
            }
        } catch (IOException e) {
            e.printStackTrace();
        }

        if (count >= 150) {
            JOptionPane.showMessageDialog(null, "No hay más boletas disponibles");
        } else {
            Global.eventoActual = "Ópera";
            Global.cursoActual = null;
            NuevoRegistro ventanaNuevoRegistro = new NuevoRegistro();
            this.setVisible(false);
            ventanaNuevoRegistro.setVisible(true);
        }
    }//GEN-LAST:event_inscribirmeOperaActionPerformed

    private void inscribirmeDanzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inscribirmeDanzaActionPerformed
        String csvFile = "RegistroUsuario.csv";
        String line;
        String csvSplitBy = ";";
        int count = 0;

        try (BufferedReader br = new BufferedReader(new FileReader(csvFile))) {
            while ((line = br.readLine()) != null) {
                String[] data = line.split(csvSplitBy);
                if (data.length > 8 && "Danza".equals(data[8])) {
                    count++;
                }
            }
        } catch (IOException e) {
            e.printStackTrace();
        }

        if (count >= 150) {
            JOptionPane.showMessageDialog(null, "No hay más boletas disponibles");
        } else {
            Global.eventoActual = "Danza";
            Global.cursoActual = null;
            NuevoRegistro ventanaNuevoRegistro = new NuevoRegistro();
            this.setVisible(false);
            ventanaNuevoRegistro.setVisible(true);
        }
    }//GEN-LAST:event_inscribirmeDanzaActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        // TODO add your handling code here:
        Index ventanaIndex = new Index();
        this.setVisible(false);
        ventanaIndex.setVisible(true);
    }//GEN-LAST:event_salirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Eventos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Eventos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Eventos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Eventos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Eventos().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel danza;
    private javax.swing.JLabel eventosDisponibles;
    private javax.swing.JPanel fondoOpera;
    private javax.swing.JPanel fondoOpera1;
    private javax.swing.JPanel fondoOpera4;
    private javax.swing.JButton inscribirmeDanza;
    private javax.swing.JButton inscribirmeOpera;
    private javax.swing.JButton inscribirmeTeatro;
    private javax.swing.JButton jButton10;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel opera;
    private javax.swing.JLabel opera1;
    private javax.swing.JButton salir;
    private javax.swing.JLabel teatro;
    // End of variables declaration//GEN-END:variables
}
