/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventanas;

/**
 *
 * @author NATALIA
 */
public class OpcionesRegistro extends javax.swing.JFrame {

    /**
     * Creates new form OpcionesRegistro
     */
    public OpcionesRegistro() {
        initComponents();
        this.setDefaultCloseOperation(HIDE_ON_CLOSE);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        eventosInscritosButton = new javax.swing.JButton();
        actualizarInformacionButton = new javax.swing.JButton();
        constanciaMatriculaButton = new javax.swing.JButton();
        eliminarRegistroButton = new javax.swing.JButton();
        salir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(230, 223, 229));
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 644));

        eventosInscritosButton.setBackground(new java.awt.Color(231, 185, 187));
        eventosInscritosButton.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        eventosInscritosButton.setText("Eventos Inscritos");
        eventosInscritosButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        eventosInscritosButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        eventosInscritosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eventosInscritosButtonActionPerformed(evt);
            }
        });

        actualizarInformacionButton.setBackground(new java.awt.Color(231, 185, 187));
        actualizarInformacionButton.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        actualizarInformacionButton.setText("Actualizar Información");
        actualizarInformacionButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        actualizarInformacionButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        actualizarInformacionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarInformacionButtonActionPerformed(evt);
            }
        });

        constanciaMatriculaButton.setBackground(new java.awt.Color(231, 185, 187));
        constanciaMatriculaButton.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        constanciaMatriculaButton.setText("Constancia de Registro");
        constanciaMatriculaButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        constanciaMatriculaButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        constanciaMatriculaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                constanciaMatriculaButtonActionPerformed(evt);
            }
        });

        eliminarRegistroButton.setBackground(new java.awt.Color(231, 185, 187));
        eliminarRegistroButton.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        eliminarRegistroButton.setText("Eliminar Registro");
        eliminarRegistroButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        eliminarRegistroButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        eliminarRegistroButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarRegistroButtonActionPerformed(evt);
            }
        });

        salir.setBackground(new java.awt.Color(231, 185, 187));
        salir.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        salir.setText("Salir");
        salir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(275, 275, 275)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(eliminarRegistroButton, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(actualizarInformacionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(eventosInscritosButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(constanciaMatriculaButton, javax.swing.GroupLayout.DEFAULT_SIZE, 455, Short.MAX_VALUE)
                        .addComponent(salir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(272, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(constanciaMatriculaButton)
                .addGap(50, 50, 50)
                .addComponent(eventosInscritosButton)
                .addGap(50, 50, 50)
                .addComponent(actualizarInformacionButton)
                .addGap(50, 50, 50)
                .addComponent(eliminarRegistroButton)
                .addGap(50, 50, 50)
                .addComponent(salir, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(119, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1002, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void eventosInscritosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eventosInscritosButtonActionPerformed
        // TODO add your handling code here:
        ConstanciaEventosInscritos ventanaConstanciaEventosInscritos = new ConstanciaEventosInscritos();
        this.setVisible(false);
        ventanaConstanciaEventosInscritos.setVisible(true);
    }//GEN-LAST:event_eventosInscritosButtonActionPerformed

    private void actualizarInformacionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarInformacionButtonActionPerformed
        // TODO add your handling code here:
        ActualizarInformacion ventanaActualizarInformacion = new ActualizarInformacion();
        this.setVisible(false);
        ventanaActualizarInformacion.setVisible(true);
    }//GEN-LAST:event_actualizarInformacionButtonActionPerformed

    private void constanciaMatriculaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_constanciaMatriculaButtonActionPerformed
        // TODO add your handling code here:
        ConstanciaCursosInscritos ventanaConstanciaCursosInscritos = new ConstanciaCursosInscritos();
        this.setVisible(false);
        ventanaConstanciaCursosInscritos.setVisible(true);
    }//GEN-LAST:event_constanciaMatriculaButtonActionPerformed

    private void eliminarRegistroButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarRegistroButtonActionPerformed
        // TODO add your handling code here:
        EliminarRegistro ventanaEliminarRegistro = new EliminarRegistro();
        this.setVisible(false);
        ventanaEliminarRegistro.setVisible(true);
    }//GEN-LAST:event_eliminarRegistroButtonActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        // TODO add your handling code here:
        Index ventanaIndex = new Index();
        this.setVisible(false);
        ventanaIndex.setVisible(true);
    }//GEN-LAST:event_salirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OpcionesRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OpcionesRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OpcionesRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OpcionesRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OpcionesRegistro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actualizarInformacionButton;
    private javax.swing.JButton constanciaMatriculaButton;
    private javax.swing.JButton eliminarRegistroButton;
    private javax.swing.JButton eventosInscritosButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton salir;
    // End of variables declaration//GEN-END:variables
}
